from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
import time

def test_nopcom():
    driver=webdriver.Chrome()
    driver.maximize_window()
    driver.get("https://demo.nopcommerce.com/")
    print(driver.title)
    print(driver.current_url)
    time.sleep(2)
    ser=driver.find_element(By.ID, "small-searchterms")
    time.sleep(2)
    print(ser.is_displayed())
    print(ser.is_enabled())
    time.sleep(2)
    poll=driver.find_element(By.NAME, "pollanswers-1")
    poll.click()
    print(poll.is_displayed())
    print(poll.is_enabled())
    print(poll.is_selected())
    time.sleep(2)
    elem = driver.find_elements(By.XPATH, "//div[@class='footer-upper']")
    print(len(elem))
    for elemt in elem:
        print(elemt.text, elemt.get_attribute('href'))
    driver.find_element(By.XPATH, '/html/body/div[6]/div[1]/div[1]/div[2]/div[1]/ul/li[1]/a' ).click()
    driver.find_element(By.ID, "gender-male").click()
    time.sleep(3)
    driver.find_element(By.XPATH, "//input[@id='FirstName']").send_keys("basava")
    driver.find_element(By.XPATH, "//input[@id='LastName']").send_keys("raja")
    day=Select(driver.find_element(By.XPATH, "//select[@name='DateOfBirthDay']"))
    day.select_by_visible_text("10")
    month=Select(driver.find_element(By.XPATH, "//select[@name='DateOfBirthMonth']"))
    month.select_by_visible_text("June")
    year=Select(driver.find_element(By.XPATH, "//select[@name='DateOfBirthYear']"))
    year.select_by_visible_text("1995")
    driver.find_element(By.XPATH, '//input[@id="Email"]').send_keys("basava.raju949@gmail.com")
    time.sleep(3)
    driver.find_element(By.XPATH, "//input[@id='Company']").send_keys("nexgen")
    driver.find_element(By.XPATH, "//input[@type='password']").send_keys("basava@949")
    driver.find_element(By.XPATH, "//input[@name='ConfirmPassword']").send_keys("basava@949")
    time.sleep(4)
    driver.find_element(By.XPATH, "//button[@id='register-button']").click()
    time.sleep(4)
    # driver.find_element(By.LINK_TEXT, "Continue").click()

    driver.get('https://demo.nopcommerce.com/login?returnUrl=%2F')
    time.sleep(3)
    driver.find_element(By.ID, "Email").send_keys('basava.raju949@gmail.com')
    driver.find_element(By.ID, "Password").send_keys('basava@949')
    time.sleep(2)
    driver.find_element(By.XPATH, "//button[normalize-space()='Log in']").click()
    time.sleep(20)

    driver.close()