login_username_locetor="phps_usern"
login_password_locetor="phps_passwd"
login_button_locetor="phps_login"
ms0_expection="/html/body/div[1]/div/span"
ms_expection="//*[@id='cloud-intro']/div/div/div[1]/div"
ms1_expection = "//*[text()='Your password must be at least 6 characters']"